name: Setting workflow
on: push

jobs:
  build:
    runs-on: macos-latest

    steps:
   - uses: actions/checkout@v2
   - name: setup node.js version 18
        uses: actions/setup-node@v3
        with:
          node-version: '18' 
    - run: make setup
    - run: make test
    - run: make lint
