name: Setting workflow
on: push

jobs:
  build:
  runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - run: npm ci
    - run: npm test
    - run: npm install
    - run: npm run lint
    - name: run tests
      run: npm test

