name: Setting workflow
on: push

jobs:
  build:
    runs-on: macos-latest

  steps:
   - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: npm
      - run: make setup
    - run: npm ci
    - run: npm test
    - run: npm install
    - run: npm run lint
    - name: run tests
      run: npm test

